[tool.poetry]
name = "forsale"
version = "0.1.0"
description = "Script for calculating For Sale distributions"
authors = ["Peter Kufahl"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
